# Configuration for Alacritty, the GPU-accelerated terminal emulator

[font]
  normal = { family = "JetBrains Mono", style = "Medium" }
  bold = { family = "JetBrains Mono", style = "Bold" }
  italic = { family = "JetBrains Mono", style = "MediumItalic" }
  bold_italic = { family = "JetBrains Mono", style = "BoldItalic" }
  size = 13

#colors.draw_bold_text_with_bright_colors = true

